name: Feature
description: Propose a new capability or improvement.
title: "[Feature]:"
type: Feature
projects: ["SkoonEnergy/3"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing an improvement.
  - type: textarea
    id: proposal
    attributes:
      label: What would you like?
      description: Describe the feature or improvement you have in mind.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add the problem it solves, examples, links, or any other useful details.
    validations:
      required: false
